### ISSUE TITLE
Add option to disable autostart

### ISSUE THREAD

**Issue by tomconte** [libretro/fuse-libretro#101]
So that the the system menus can be accessed, and the program can be launched manually from the BASIC command line.

- Add new core option
- Make sure the games can be launched without a need to start the tape

**Comment by snoofly** [comment]
Look forward to seeing this option.
Typed LOAD “” <enter> so many times as a kid
Can you add another option to emulate R: Tape loading error right at the end as well ;)

**Comment by zzedmore** [comment]
Is this a possibility ? Will it still load after typing `LOAD""` or will turning off autostart require you to press play ?

**Comment by zzedmore** [comment]
Just tried this on regular FUSE and turning off autostart does still start the tape automatically after typing LOAD"". So the option is already in the FUSE code, just need a reference to it in the Retroarch core. This means we could type BASIC programs ! (but have to save them as States).
