### ISSUE TITLE
Stoped working on WiiU!

### ISSUE THREAD

**Issue by ruijtunes** [libretro/fuse-libretro#105]
After the commits  on Apr 3, 2021 it stoped working on Wiiu.

**Comment by tomconte** [comment]
Have you tried with the more recent builds? There were additional fixes after April 3...

Otherwise, do you have an error message or a stack trace?

**Comment by ruijtunes** [comment]
Yes I have tried with newer builds. After 3/4/2021 they all fail.
In attach are 4 log files. The first one ("retroarch__2021_05_26__19_54_16.log") is with the build from 29/3/2021, it all run fine.
The others are from the latest buil from 26/5/2021. It failed.


[retroarch__2021_05_26__20_02_42.log](https://github.com/libretro/fuse-libretro/files/6549411/retroarch__2021_05_26__20_02_42.log)
[retroarch__2021_05_26__20_06_21.log](https://github.com/libretro/fuse-libretro/files/6549412/retroarch__2021_05_26__20_06_21.log)
[retroarch__2021_05_26__20_09_53.log](https://github.com/libretro/fuse-libretro/files/6549413/retroarch__2021_05_26__20_09_53.log)
[retroarch__2021_05_26__19_54_16.log](https://github.com/libretro/fuse-libretro/files/6549414/retroarch__2021_05_26__19_54_16.log)

**Comment by tomconte** [comment]
Thanks for the logs! I think I have a fix for that issue 🤞

Could you try this build: https://git.libretro.com/libretro/fuse-libretro/-/jobs/416333/artifacts/browse

**Comment by ruijtunes** [comment]
Yes!! It Works just fine.

Thank you

**Comment by tomconte** [comment]
Thanks for testing! I have merged the fix.
