### ISSUE TITLE
tzx images will not load if "fast load" enabled

### ISSUE THREAD

**Issue by Pete-McDonald** [libretro/fuse-libretro#113]
Hi All,

First, thanks for the awesome work you do.   I'm trying to use fuse within Retroarch to load Spectrum 48K games.

Using RetroArch 1.9.7 (and saw this in 1.9.5) RA crashes on trying to load a tzx image if "Fast Load" is enabled.  Have tried many tzx images and all are affected. z80 seems to work just fine.

When fast load is disabled, it shows a grey sinclair 1982 screen - and I hear the nostalgic loading sound.  I will leave it running to see if it loads, as I quit out after a couple of mins so will leave it over night tonight :)

Let me know what you need to investigate this further.

**Comment by tomconte** [comment]
Hi and thanks for your report!

On which platform did you see this behaviour? I just tested a TZX image with RetroArch 1.9.7 on Raspberry Pi (via RetroPie) and it worked fine.

Also, could you link to a TZX file that triggers the problem, and any error or log messages from RetroArch?

**Comment by Pete-McDonald** [comment]
Hi Tom,

Thanks so much for your quick response.  I was testing this on Win x64.

Your message got me to try a clean install of RA and Fuse on a different PC - and it loaded a tzx just fine. Apologies for wasting your time, it must be something on that particular machine!
