### ISSUE TITLE
Default keyboard

### ISSUE THREAD

**Issue by Roolandoo** [libretro/fuse-libretro#117]
Hi,
I am a homebrew ZX Spectrum games developer and I am trying to find a method to "package" the FUSE emulator and my game, so that the NON-RETRO player does not have to fight with the emulator (as if it were a Windows game).

To do this, I found this tool  [https://github.com/kivutar/rombundler] that uses **fuse_libretro.dll** and creates an .EXE that runs the game transparently to the user.

Everything works perfect but the problem is that in fuse_libretro by default the keyboard is not activated (but the joystick is). This is not operational for all users and I cannot find the Core Options to change this.

**Is there any solution?**

Greetings and thanks in advance.

**Comment by leiradel** [comment]
You have to configure port 3 in the frontend to use the Sinclair Keyboard, take a look [here](https://docs.libretro.com/library/fuse/). However, it doesn't seem that ROMBundler has an option for that.

**Comment by Roolandoo** [comment]
Yes, I know, Leiradel.
That is precisely the problem: that ROMBundler does not have a Frontend. Only have access to the main options.

**Is there any other way to activate the keyboard by default?**

**Comment by leiradel** [comment]
Technically speaking, ROMBundler **is** a Libretro frontend, but that's beside the point.

Activating the keyboard by default requires changes in the Fuse core. Adding an option to assign the Sinclair Keyboard to a port requires changes to ROMBundler.

My opinion is that ROMBundler should provide options in its config file to allow the assignment of devices to ports, as this also benefits other cores. It shouldn't be hard to do it. @kivutar ?

**Comment by Roolandoo** [comment]
This issue is now resolved thanks to @kivutar adding keyboard support in ROMBundler.
Thanks for everything.
