### ISSUE TITLE
Unable to use control pad with fuse-libretro

### ISSUE THREAD

**Issue by neilmunday** [libretro/fuse-libretro#12]
Hi,

I apologies in advance if this is user error...

I have been trying to use my PlayStation 3 control pads with fuse-libretro but the only button that the emulator responds to is the select button which brings up the keyboard overlay. No matter what buttons I press the emulator does not respond to the input (even the overlay).

The control pads work fine with all the other emulator cores that I use with RetroArch. Am I missing something?

Thanks,

Neil.

**Comment by leiradel** [comment]
Hi,

Go to RetroArch's input settings, set the first controller to Kempston, and try again.

Cheers,

Andre

**Comment by neilmunday** [comment]
Hi Andre,

Thanks for the quick response - that did the trick. I clearly missed it when hunting through all the options yesterday!

Cheers,

Neil.

**Comment by leiradel** [comment]
Glad it worked!
