### ISSUE TITLE
Support SCL files

### ISSUE THREAD

**Issue by leiradel** [libretro/fuse-libretro#15]

**Comment by leiradel** [comment]
@windale, please point me to a SCL file that you know for sure that works, and give me detailed instructions on how I run it.

I've put everything in place to load SCL files but I don't know how to use TR-DOS, so I'm unable to test and commit the changes.

**Comment by leiradel** [comment]
No need for that, support for SCL files was added with the latest commit.

**Comment by windale** [comment]
I'm having trouble getting any of these to work. Does FUSE need more roms baked ? I have tried several from this site http://vtrdos.ru/ all unzipped, but none of them want to load. I have tried setting the Retroarch option to Scorpion 256K but no result. They work fine on PC (Spectaculator) and Nintendo DS (ZXDS).
