### ISSUE TITLE
How do you open the menu ? No buttons work ?

### ISSUE THREAD

**Issue by windale** [libretro/fuse-libretro#17]
I just updated to RetroPie 3 beta 3 and can't get any buttons to work except the Select button which brings up the on-screen keyboard. USB keyboard doesn't work either ?

**Comment by leiradel** [comment]
The RetroArch menu is activated with F1. Try to configure the inputs as follows:

User 1: Cursor Joystick
User 2: Kempston Joystick
User 3: Sinclair Keyboard

Let me know if it works.

**Comment by windale** [comment]
I can't press F1 because none of the keys work on the external keyboard. If I enter the Retroarch menu with my Joypad (Hotkey+SNES Pad button X) the Retroarch menu comes up and says press X etc. to continue but no buttons work. I have to turn off the Pi.

**Comment by leiradel** [comment]
So it doesn't seem to be an issue in the fuse core. I suggest you to open an issue for RetroArch instead.

If the fuse core controllers continue *not* working after you solve the problem in RetroArch, please reopen this issue.
