### ISSUE TITLE
MAX_PATH undeclared

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/fuse-libretro#18]
Trying to build for linux

```
src/compat/file.c:164:16: error: 'MAX_PATH' undeclared (first use in this function)
    char system[MAX_PATH];
                ^
```

https://launchpadlibrarian.net/209095601/buildlog_ubuntu-trusty-amd64.libretro-fuse_1.1.1%2Br72~2~ubuntu14.04.1_BUILDING.txt.gz

**Comment by leiradel** [comment]
Fixed, thanks for the report.
