### ISSUE TITLE
zlib header error in the build

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/fuse-libretro#19]
Another issue now, why the core is using zlib? And what's this "git not found" ?

```
cc -c -o fuse/movie.o fuse/movie.c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -O3 -DLOG_PERFORMANCE -fPIC -D__LIBRETRO__  -DGITHASH=\"`git rev-parse HEAD`\" -DHAVE_CONFIG_H -Wall  -I. -I./src -I./fuse -I./libspectrum
/bin/sh: 1: git: not found
fuse/movie.c:37:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make[2]: *** [fuse/movie.o] Error 1
```

https://launchpadlibrarian.net/209179035/buildlog_ubuntu-trusty-amd64.libretro-fuse_1.1.1%2Br74~2~ubuntu14.04.1_BUILDING.txt.gz

**Comment by leiradel** [comment]
I've added zlib and bzip2 to the include path, the build should work now, but I'll leave the issue open until it can be validated.

zlib and bzip2 were added to support file formats with compression, like RZX.

**Comment by leiradel** [comment]
And git is used to add the commit hash to the build, so the core outputs it when it's loaded and reports can refer to a specific version.

**Comment by leiradel** [comment]
@sergiobenrocha2 any word about this?

**Comment by sergiobenrocha2** [comment]
It's working, thanks!
