### ISSUE TITLE
SCL & TRD compatibility.

### ISSUE THREAD

**Issue by windale** [libretro/fuse-libretro#23]
I'm having trouble getting any SCL files to work. Does FUSE need more roms baked ? I have tried several from this site http://vtrdos.ru/ all unzipped, but none of them want to load. I have tried setting the Retroarch option to Scorpion 256K but no result. They work fine on PC (Spectaculator) and Nintendo DS (ZXDS).

I also cannot get TRD files to work. I tried Metal Man Reloaded from http://www.olegorigin.org/metal_man_reloaded.html (TRD version unzipped).

**Comment by leiradel** [comment]
Pentagon and Scorpion machines need additional ROMs to work. Please follow the instructions at https://github.com/libretro/fuse-libretro/blob/master/README.md under the **Emulated Machines** section and let me know if it solves the problem of loading `SCL` and `TRD` files.

**Comment by windale** [comment]
I'm not sure where to put the roms in retropie. The link you showed me said to put the roms in a 'fuse' folder inside the <system> folder. I put them in -

/opt/retropie/libretrocores/lr-fuse/fuse

it didn't work, I also tried -

/opt/retropie/libretrocores/lr-fuse

This is the log file -

retro_read_file: Failed to open /home/pi/RetroPie/roms/zxspectrum/Action Force I + II (1987) (Virgin Games).ips: No such file or directory
retro_read_file: Failed to open /home/pi/RetroPie/roms/zxspectrum/Action Force I + II (1987) (Virgin Games).bps: No such file or directory
retro_read_file: Failed to open /home/pi/RetroPie/roms/zxspectrum/Action Force I + II (1987) (Virgin Games).ups: No such file or directory
fuse: error: couldn't find ROM '256s-0.rom'

The game is actually a single SCL file, I don't know what ips/bps/ups are.

**Comment by leiradel** [comment]
You have to check in RetroArch where the `system` folder is located, and follow the instructions in the previous link.

**Comment by windale** [comment]
In RetroPie it says the RetroArch system directory is in -
system_directory = /home/pi/RetroPie/BIOS

I put the following roms in there but it still says 'couldn't find ROM'

128p-0.rom   128p-1.rom
256s-0.rom   256s-1.rom   256s-2.rom   256s-3.rom
gluck.rom
if1-1.rom   if1-2.rom
opus.rom
trdos.rom

**Comment by leiradel** [comment]
Create a `fuse` folder under the system folder and move the ROMs there.

**Comment by windale** [comment]
O.K. i'm slowly getting somewhere now. I put the roms in a fuse folder. The TRD file works, but the SCL files just go to the white TRDOS screen with a command prompt at the bottom. If I type LIST it shows the inserted disk but it's not auto-booting.

**Comment by windale** [comment]
Is there any chance you could make these auto-boot ?

If you type LIST it shows you the names on the disk, the ones with <B> next to them are bootable. Load them by typing LOAD "filename". (The filenames are case sensitive). You probably know all this already.

Also, in TRDOS the Q and W keys on the keyboard don't seem to work so some filenames are impossible to type. They work once in game though (I only tried 1 game to test).

**Comment by leiradel** [comment]
Auto-booting a file from a disk image is not the job of the emulator. You can write a TR-DOS autoboot file that does the right thing (TM) for each disk image.

As for the keys, you can enable a hotkey in RetroArch to make the entire keyboard available for the emulator. You can also press select to bring up the virtual keyboard and use it to send keystrokes to the emulator.

I'm closing this issue since SCL and TRD images are working fine.

**Comment by belowzero273** [comment]
@leiradel I'm facing the same problem, did you find a proper solution? Where do you put those rom files to make scl files work?

**Comment by leiradel** [comment]
Hi,

You only need additional ROM files for the Pentagon 128K, 512K, and 2014, and the Scorpion 256K. If you really need additional ROMs, check what is your `system_directory` in `retroarch.cfg`, create a folder named `fuse` in it, and put your ROMs there.

When in doubt, check the `.rom` files [here](https://github.com/libretro/fuse-libretro/tree/master/fuse/roms) to see which ROMs are built into the core. You only need to manually copy ROMs that aren't there.

Also, I believe you need at least a Spectrum +2 to run disk images, but I'm not 100% sure. I only had a Spectrum 48K.

**Comment by belowzero273** [comment]
@leiradel the system folder is default /home/pi/RetroPie/BIOS, so I put all the roms in /home/pi/RetroPie/BIOS/fuse, but I still get "fuse error couldn't find rom '128p-0.rom'". Where to dig next?

**Comment by leiradel** [comment]
Could you turn on verbose logging and paste it her please? Thanks.

**Comment by belowzero273** [comment]
@leiradel ha, found it with verbose logging - another spelling error =) I get to TRDOS and should get file list with LIST command and then LOAD them. But for some reason it autocompletes L to LET, should google for tr dos commands I think.

**Comment by leiradel** [comment]
So it's working as expected, right? Cool.

**Comment by belowzero273** [comment]
yep, found all the necessary already, thanks!

**Comment by leiradel** [comment]
np
