### ISSUE TITLE
Shift keys should be toggle keys on the virtual keyboard

### ISSUE THREAD

**Issue by leiradel** [libretro/fuse-libretro#25]
I'll try to port the virtual keyboard code from 81-libretro as it has toggle keys built-in.

**Comment by snoofly** [comment]
A workaround I use for not having sticky shift keys is to map Caps and Symbol to L2 and R2.
Then you can effect accessing the extended keywords, characters etc by keeping the trigger down whilst pressing - to bring up the keyboard.
Would be good to see sticky shift implemented properly though.
