### ISSUE TITLE
temp, Can you please leave the thread open, I had something to report back on the last thread you closed

### ISSUE THREAD

**Issue by windale** [libretro/fuse-libretro#26]
Regarding the keyboard issue, as I said in the other thread before you closed it again, in LR-Fuse the Q and W keys dont work in TRDOS but when I loaded a text adventure (Neverending Story & Hunchback), the Q and W keys work. If it was down to Retro-Arch then they wouldn't work in-game either ?

Regarding the auto-boot, in the PC emulator Spectaculator and ZXDS. There is an option (On by default) to "automatically load and run first program in SCL files". It seems to work fine on every SCL file i've ever tried.

**Comment by leiradel** [comment]
Ok, I've split the issues for you.
