### ISSUE TITLE
Problems with some keys in TR-DOS

### ISSUE THREAD

**Issue by leiradel** [libretro/fuse-libretro#28]
@windale said

"Regarding the keyboard issue, as I said in the other thread before you closed it again, in LR-Fuse the Q and W keys dont work in TRDOS but when I loaded a text adventure (Neverending Story & Hunchback), the Q and W keys work. If it was down to Retro-Arch then they wouldn't work in-game either ?"

I'll try to reproduce the problem.

**Comment by leiradel** [comment]
@windale can you provide a link to download one of the disk images you mentioned as having problems with the keyboard? I can only find tape images.

**Comment by leiradel** [comment]
@windale, I've tried Viking Quest 1 and I think I know what your problem is. First make sure you have a hotkey defined in RetroArch. Go to:

**Settings tab -> Input -> Input Hotkey Binds -> Enable hotkeys**

and define a key that will enable all other RetroArch hotkeys (I use `tilde`). What that means in practice is that you'll no longer be able to access the menu by pressing F1, you'll have to press both the `enable hotkey` key and `F1`. The same goes to all other RetroArch hotkeys. This will make all key presses go to the emulator.

Well, almost all. Some keys are bound to the RetroPad, so when you press them no key presses are sent to the emulator. As an example, the `Q` and `W` keys are mapped to the RetroPad buttons `L` and `R` by default, so they're not passed to the core as key presses, but as joystick button presses instead.

To play text adventures, the best thing to do is to remove any controllers attached to the core. So, after starting the core, press `enable hotkey` + `F1`, go to **Core Input Options**, and set **User 1 Device Type** to **None**.

Please let me know if that fixes this issue.

**Comment by windale** [comment]
I don't have a hotkey assigned on the keyboard, only on the joypad (Select+X). As I said, on some games the Q and W keys work, like the Hunchback link below. Note, you also have to type RUN after manually loading the SCL.

http://vtrdos.ru/gamez/h/HUNCH_3_.ZIP

Do the Q and W keys work on yours when in the TRDOS Beta 128 screen (at the bottom where you type the commands) ? When the games are actually loaded, the Q and W keys work on some and not on others, weird. I also tried the Spectrum +3 menu and can hear the sound effect when pressing all the keys except Q and W.

I think i'll give up on this and use the regular version of FUSE.

**Comment by leiradel** [comment]
I've just tested Hunchback and all keys, including `Q` and `W`, work just fine both in TR-DOS, before loading the game, and in the game. Actually the number keys don't work inside the game (they do inside TR-DOS), but I've tested Kayleth and all keys work so it's definitely a problem with Hunchback.

I'm positive that all you have to do is to configure RetroArch and the Fuse core as instructed before. If you do that and the keys still don't work please comment here and I'll reopen this issue.

And yes, you have to manually run Hunchback with `RUN "Hunch 3+"` as the SCL disk image doesn't include an autoboot file. There's an enhancement request just for that, but so far nobody has sent a pull request with a patch to make the core autorun an executable file in disk images.
