### ISSUE TITLE
Fuse iOS port?

### ISSUE THREAD

**Issue by MaquinaDelMisterio** [libretro/fuse-libretro#40]
A guy told me that there was a working fuse core, but is there a port for iOS?

**Comment by leiradel** [comment]
The Fuse core compiles for iOS, but was not being bundled with RetroArch. @twinaphex added it and it should be available soon, but I don't know exactly when.

**Comment by MaquinaDelMisterio** [comment]
Thanks, its already avaiable.

**Comment by leiradel** [comment]
Awesome, thanks for letting me know.
