### ISSUE TITLE
Page Fault Crash on N3DS

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/fuse-libretro#51]
Tried loading these .z80 files:

- JetPac
- JetSet Willy

1.7.1 - fuse 1.1.1 58ec13f

## Crash

![img_1655](https://user-images.githubusercontent.com/49612/38624755-ce23f596-3da0-11e8-8ffb-ae4c53aa340d.jpg)

## Parsed Dump

[crash_dump_00000024.dmp.txt](https://github.com/libretro/fuse-libretro/files/1899346/crash_dump_00000024.dmp.txt)

## Raw Dump

[crash_dump_00000024.dmp.zip](https://github.com/libretro/fuse-libretro/files/1899340/crash_dump_00000024.dmp.zip)

**Comment by Ulrichbc** [comment]
I have the same problem. Using latest Nightly build, put the bios roms in retroarch/cores/system/fuse, N3DS and old 3DS as well...
Would be awesome if someone could help us fix this error.
Is there anyone who has got this working?

**Comment by leiradel** [comment]
Does this happen with only those two games, or with any game?

**Comment by Nigey777** [comment]
Every game i've tried does the same even with the newest update, quite frustrating considering much more complex emulators work. Would be great if this could work.

**Comment by Nigey777** [comment]
i've tried .tap files still error :(

**Comment by Nigey777** [comment]
I have tried this on a 3ds and 2ds

**Comment by gingerbeardman** [comment]
Is your Luma/BS9 setup current?

**Comment by Nigey777** [comment]
yes it is, all up to date, ive totally uninstalled retroarch and tried re installing still the same every time. Have you got it working then??

**Comment by gingerbeardman** [comment]
No, this is still broken for me. 

But listing this information is useful for the developers.

My New 3DS:

- System = 11.11.0-43E
- Luma = 10.0.1-c913de1
- B9S = 1.3 (6 Sep 2017)

What versions of everything are you running?

- RetroArch = 1.7.8 fuse 1.1.1 8184756

There seems to be some cross-compatibility between the EightOne and FUSE cores as things load in one when I specify the other.

**Comment by Nigey777** [comment]
I will have a look somewhen. I don't hold much hope as they haven't replied to me on Facebook.
