### ISSUE TITLE
.POK support

### ISSUE THREAD

**Issue by SaucySarah** [libretro/fuse-libretro#53]
Hi, do pokes work with this libretro version and if so how to choose what cheats to apply ?

**Comment by leiradel** [comment]
Can you point me to some POK files? Thanks.

**Comment by SaucySarah** [comment]
http://www.the-tipshop.co.uk
https://github.com/eklipse2009/ZX-Pokemaster

**Comment by leiradel** [comment]
Thanks, I'll look into it

**Comment by SaucySarah** [comment]
May as well close this as well as not much hope in seeing it implemented.

**Comment by leiradel** [comment]
Implemented in https://github.com/libretro/fuse-libretro/commit/5a024e2da4a8ef12d91508646744ab14cae2cd49

Note: POK files don't work directly, they have been converted to the RetroArch format and must be downloaded from [here](https://github.com/libretro/libretro-database/tree/master/cht/Sinclair%20-%20ZX%20Spectrum%20%2B3).
