### ISSUE TITLE
A way to enter spectrum Pokes

### ISSUE THREAD

**Issue by lordvek3** [libretro/fuse-libretro#57]
Is it possible to implement a way to enter Pokes for unlimited lives, energy etc or build-in Multiface emulation in a future update of lr-Fuse?

**Comment by SaucySarah** [comment]
I asked for this here https://github.com/libretro/fuse-libretro/issues/53 nearly 3 months ago. No point in asking really as it's like tryng to get blood out of a stone ! This port is several years old compared to the original FUSE that it's based on. This is as good as it's going to get. Best to use the original Fuse if possible.

**Comment by leiradel** [comment]
> Is it possible to implement a way to enter Pokes for unlimited lives

It's definitely possible, but I, the only maintainer of this port, have other priorities right now.

If you happen to be a software developer, or know someone who is, and is interested in emulation, the libretro project is always open for new contributors.

**Comment by leiradel** [comment]
Other ways to help are to [be a patron](https://www.patreon.com/libretro), or to [fund for features](https://www.bountysource.com/teams/libretro/bounties) you want to see in the project.

**Comment by lordvek3** [comment]
I saw this SaucySarah, but you ask for pok files. I mean a different approach, to be able somehow to write values to the "memory" addresses of Spectrum directly. How difficult can it be?

**Comment by lordvek3** [comment]
I just offered $15 to the bountysource page for the feature I asked for. Can I hope?

**Comment by leiradel** [comment]
The problem is that RetroArch has its own cheat file format, POK files won't work with it. I'm talking to the other developers about converting all POK files from Tipshop and making them available somewhere.

**Comment by leiradel** [comment]
Well, @RobLoach was kind enough to convert all the POK files from the [Tipshop](https://github.com/eklipse2009/all-tipshop-pokes) to the [RetroArch format](https://github.com/libretro/libretro-database/tree/b3fdaa95f3981c1bec58128f3e4b2c589b6c2a92/cht/Sinclair%20-%20ZX%20Spectrum%20%2B3).

I still have to code the functionality into the core and see if it works, but we're halfway through.

**Comment by lordvek3** [comment]
Thank you guys! I am looking forward to see it!

**Comment by leiradel** [comment]
Implemented in https://github.com/libretro/fuse-libretro/commit/5a024e2da4a8ef12d91508646744ab14cae2cd49

**Comment by leiradel** [comment]
Note: POK files don't work directly, they have been converted to the RetroArch format and must be downloaded from [here](https://github.com/libretro/libretro-database/tree/master/cht/Sinclair%20-%20ZX%20Spectrum%20%2B3).

**Comment by lordvek3** [comment]
I tried them and they are working perfect. A big thanks to you my friends Andre and Rob for the immediate response. Be well, and thank you again!!!

**Comment by leiradel** [comment]
Np, glad it's working!

**Comment by leiradel** [comment]
@lordvek3 where is the bounty? I want to reclaim it and give it to the libretro project.

**Comment by lordvek3** [comment]
Here, in that page:
https://www.bountysource.com/issues/62280633-a-way-to-enter-spectrum-pokes
I associated it with the issue. I don't know exactly how this is working, but there is a button "Claim Bounty"

**Comment by RobLoach** [comment]
Thanks for contributing and getting this going! :heart:

**Comment by lordvek3** [comment]
And I thank you guys for you work about entering cheats on lr-fuse! Be well!
