### ISSUE TITLE
Core doesn't load on Android GPD XD handheld

### ISSUE THREAD

**Issue by 2xtime** [libretro/fuse-libretro#61]
If I go to the Core Updater and download the FUSE core then Load the Core it doesn't do anything. It still says '1.7.5 - No Core' at the bottom left of the screen. If I load Content it says 'Failed to open Libretro Core'.
Is there a correct version for my device or is it building an incompatible one ? My device is NOT Rooted so I don't have access to any Retroarch logs. I noticed someone recently added support for the Cortex A7, could you add support for the Cortex A17 please ? Maybe this is why it doesn't work.

My device
Android 4.4.4
Rockchip RK3288 SoC, ARM Cortex-A17
Mali-T764

**Comment by 2xtime** [comment]
@leiradel Any chance you could do this ? No idea why it won't download the core. Is my device and ARM version in the makefile ? The Cortex-A17 uses ARM v7a so I would need the Android armeabi-v7a Fuse build.

**Comment by fr500** [comment]
Most likely the libretro buildbot targets a newer NDK.

**Comment by leiradel** [comment]
> Most likely the libretro buildbot targets a newer NDK

Would it use a different NDK for the cores in relation to RetroArch?

@2xtime did you build RetroArch yourself, or downloaded a pre-built version from the buildbot?

**Comment by 2xtime** [comment]
Downloaded from GooglePlay (v1.7.5).

**Comment by 2xtime** [comment]
So will there be a commit that can fix this please ? This is the only Core that doesn't work.

**Comment by fr500** [comment]
@leiradel it uses whatever is defined here:
https://github.com/libretro/libretro-super/blob/master/recipes/android/cores-android-cross.conf

@2xtime you don't need root to get logs, you just need ADB and to enable debugging options.
We certainly need a log to check what's up.

**Comment by leiradel** [comment]
> @leiradel it uses whatever is defined here

@fr500 So it uses the same NDK as the other cores that use the cross makefiles, right? 

@2xtime Can you check 81-libretro and gw-libretro and see if they work? We'll also need the log like @fr500 said.

**Comment by 2xtime** [comment]
Game&Watch works fine, ZX81 doesn't work. What information will you need from my log file ? Amongst lots of `GC_FOR_ALLOC` lines I can see this -

```
E/RetroArch( 2626): Failed to open libretro core: "/data/data/com.retroarch/cores/fuse_libretro_android.so"
E/RetroArch( 2626): Error(s): dlopen failed: cannot locate symbol "rand" referenced by "fuse_libretro_android.so"...
```

**Comment by leiradel** [comment]
> @leiradel, maybe add -Wno-undefined so it fails building instead :)

But it works on other Android devices. I'm not sure this would cause an error during the build. I'll add a rand replacement anyway.

@2xtime could you post the log of the ZX81 core? Maybe the missing symbol is different.

**Comment by 2xtime** [comment]
@leiradel 

```
E/RetroArch( 3120): Failed to open libretro core: "/data/data/com.retroarch/cores/81_libretro_android.so"
E/RetroArch( 3120): Error(s): dlopen failed: cannot locate symbol "stpcpy" referenced by "81_libretro_android.so"...
```

**Comment by leiradel** [comment]
> stpcpy

This should be `strcpy` right? `stpcpy` symbol doesn't exist in the entire 81-libretro codebase.

I'm not sure I should start adding replacements for those missing symbols, `strcpy` shouldn't be missing and is likely a symptom of a different issue with this device.

**Comment by 2xtime** [comment]
I just did a simple google search and saw lots of similar errors.

https://stackoverflow.com/questions/32611548/cannot-locate-symbol-rand-referenced-by-libjninice-so

Several sites say you have to change the Android API platform so it's compatible with lower Android versions, platform=19 maybe ? I'm not sure what the numbers represent because I know nothing about Android but i'm sure you or @fr500 know about this.

Considering all the cores I use work fine (10 of them) and only FUSE doesn't work (and ZX81) there must be a Android platform number that everybody uses to make it compatible on all versions of Android, (mine being KitKat 4.4.4).

**Comment by leiradel** [comment]
gw-libretro, 81-libretro, and fuse-libretro, are compiled in the exact same way by the buildbot.

@fr500 do you have any clue what could be happening?

**Comment by leiradel** [comment]
> Several sites say you have to change the Android API platform so it's compatible with lower Android versions, platform=19 maybe ?

Yeah, many search results say that lowering the API fixes those errors. We'll need help from people from the libretro team, to see what API is being used now and if it's possible to use a different one.

**Comment by 2xtime** [comment]
Yeah, hopefully this doesn't take weeks/months to do considering all the other cores work fine (out of about ten that I use but I imagine the rest will work as well) which is quite annoying. The Spectrum is in my top 2 retro systems, the other being the Amiga.

The ZX81 core (which I don't use) that also doesn't work was also ported by you ? Sorry for the dig ! Hopeful to see some of that 'correctness' you talk about :)

**Comment by leiradel** [comment]
Yeah, I hope this isn't some mistake of yours again. There are no other complaints about the cores on Android.

**Comment by 2xtime** [comment]
@leiradel I was only joking about your ports. No mistakes from me this time i'm afraid with the logs to prove it. A lot of people tend to use Raspberry Pi's and other people wouldn't even know where to report the bug anyway. So no chance of you fixing this then ?

**Comment by fr500** [comment]
seems to be a general issue with the cross makefiles for some reason

```

dru.whitfieldToday at 10:34 AM
Right I'm looking for just the older core it's self. I know how to plug it into a build.
The api on the updated core is unusually high. Will not work on anything bellow Android 5.0
I guess I will have to try and modify the updated core.
I wish I had been backing cores up.
I started a thread for the issue on github but it has stalled out.
I can't use the updated core as it is on the original Gpd Xd. That really bites.```

**Comment by 2xtime** [comment]
The core loads and works fine now, I won't say I told you so ! :)

You may wan't to add the API change to your ZX81 port too.

**Comment by leiradel** [comment]
Will do, thanks for the report.
