### ISSUE TITLE
Fuse vita version via retroarch

### ISSUE THREAD

**Issue by vitauser1** [libretro/fuse-libretro#65]
Basic install of retroarch on vita.  No virtual keyboard available.  Tried hotkey assignment but does not opn on screen keyboard? Help!

**Comment by snoofly** [comment]
Likely a setup issue more than a bug.
Check you don't have User 1 Device Type set to Retropad and put it to Kempston/Cursor etc.
Then Select should bring up the virtual keyboard.
Works for me on 1.7.7

**Comment by vitauser1** [comment]
Thank you for the reply....that worked.....thanks!
