### ISSUE TITLE
Core doesn't load after latest commit 72b3341

### ISSUE THREAD

**Issue by SaucySarah** [libretro/fuse-libretro#69]
@twinaphex  @webgeek1234 Core doesn't load, it says 'Failed to open libretro core'. It gives no information at the bottom left of the screen.

My device is a GPD XD Handheld, Android Kitkat. Retroarch v176 Stable (I can't use the latest version because there is a bug (that has been reported but not fixed) that crashes Retroarch when going to/from the GUI).

I think the problem is 'cannot locate symbol "rand" '. This is my most used core. Please fix. Thanks.

[adb log.txt](https://github.com/libretro/fuse-libretro/files/3341708/adb.log.txt)

**Comment by SaucySarah** [comment]
The same problem was reported here https://github.com/libretro/fuse-libretro/issues/61 . I think you need to lower the API to 19.

**Comment by webgeek1234** [comment]
Yeah, this looks like my bad. No idea how or why I added a target api to the jni makefiles. But the core compiles fine all the way down to the current minimum api of 16. Submitted PR #70 to fix this.

**Comment by SaucySarah** [comment]
Works again now, thanks.

**Comment by leiradel** [comment]
@webgeek1234 haven't this change been made in other cores too? Maybe the same fix should be made to them.
