### ISSUE TITLE
Baking in BIOS files

### ISSUE THREAD

**Issue by Oggom** [libretro/fuse-libretro#7]
To my knowledge most of the BIOS files for the ZX Spectrum have been released as freeware and could therefore be baked in within the libretro core to get rid of having them as an additional dependency. Mainline does includes as part of their distribution too.

Further info:
http://www.shadowmagic.org.uk/spectrum/roms.html

**Comment by leiradel** [comment]
This is done. Only 48.rom and tape_48.szx are baked within the core as they're the only ones being used by now.
