### ISSUE TITLE
Upgrade to 1.5.7 and support for multi disk (m3u)

### ISSUE THREAD

**Issue by ToniBC** [libretro/fuse-libretro#72]
Fuse is a core that is quite good, it is one of those recommended for Spectrum, but the core is quite outdated, since it uses 1.1.1 as a base and 1.5.7 already go through many corrections.

On the other hand, multi-sided multi-disc games cannot be loaded because they have no option to change discs. It is rare that the m3u disk change holder is in almost all cores except this one.

It would be nice for someone to review and update this core just like they did with Amstrad's Caprice.

Greetings and thanks for the effort.

**Comment by snoofly** [comment]
Just stopping by and wondering if any thoughts on updating the Speccy core as the Vice one has been given much TLC of late.
Appreciate what we already have though.

**Comment by ToniBC** [comment]
I am surprised that being a platform with more success than Amstrad or Commodore, this core is so stopped, without m3u support, very outdated and some errors. Now they are with Amiga's, we will see if anyone updates it, which for what they said, updating it is relatively simple and fast.

**Comment by Darknior** [comment]
Yes, so bad this great emulator was stopped :(
I also stand for m3u feature for a long time .... i wish one day some one will work again on this emulator...

**Comment by yonailo** [comment]
M3u is not needed because you can concatenate all files (tzx or tap) in a single one.
