### ISSUE TITLE
Save States - Segmentation Fault

### ISSUE THREAD

**Issue by rtomasa** [libretro/fuse-libretro#82]
Hi,

I've noticed that Save States are not working and are crashing retroarch when trying to save or load.
Segmentation Fault is displayed in CLI with no more details.
Not sure if this is correct version but Retroarch 1.8.5 reports that it is libretro fuse (1.1.1 37c8a3c)

The system is a Raspberry Pi 3 using Raspbian OS.

BR

**Comment by tomconte** [comment]
This seems to work now, using the 1.6.0 version, could you confirm? (just tested on Pi 400)

**Comment by tomconte** [comment]
I am going to close this for now, please re-open if the issues persists.
