### ISSUE TITLE
.dsk needs adding to fuse_libretro.info

### ISSUE THREAD

**Issue by zzedmore** [libretro/fuse-libretro#97]
The extension `dsk` needs adding to the supported extensions in `fuse_libretro.info`, otherwise Disk files cannot be loaded from 'Load Content'. Not sure who has to handle this change ?

**Comment by tomconte** [comment]
I have submitted the change here:

https://github.com/libretro/libretro-super/pull/1530

I think libretro-super is the source for this information, but I am not sure how long it takes for all the downstream projects to pick it up... What front-end are you using? RetroPie allows me to launch .dsk games.

**Comment by zzedmore** [comment]
I just tried it on Windows. When I select Load Content and it asks what core to use, Fuse is not listed as DSK is not in the recognized extensions. It may work using playlists. Just thought i'd point it out.

**Comment by zzedmore** [comment]
It didn't update the last time I updated the Core Info files, not sure why. It's correctly updated now. Cheers.
